### ISSUE TITLE
Bundle missing after baler configuration steps

### ISSUE THREAD

**Issue by skdude** [magento/baler#24]
Hello,

I followed all the steps in https://github.com/magento/baler/blob/master/docs/ALPHA.md
And when I ran the command 'baler' everything was looking fine. For each Magento theme I got the command line message 'Created core bundle file' and 'Minified core bundle and RequireJS', however I'm not seeing any bundle in the project. Also checking the store url I get all JS files separate so no actual bundle was generated.

Am I missing something?

Kind regards,

**Comment by DrewML** [comment]
Thanks for the report @skdude. Do you have a recommendation of how we could make this more clear? Maybe just advising where the bundle was written?

**Comment by skdude** [comment]
Hello, maybe it could be useful to add this information to the Magento 2 Baler module: https://github.com/adifucan/m2-baler. I had to go through the code to figure it out.
Everything works perfectly though. Thanks again!
