### ISSUE TITLE
Is it possible to run baler on dev machine, and deploy the results on production?

### ISSUE THREAD

**Issue by dweerd** [magento/baler#26]
On our production environment we don't have the possibility to use node, so I wonder if I can run baler on our development machine (which does run node), and use the results on our production environment..?

**Comment by krzksz** [comment]
I'm not sure bu in theory if you publish all files in `pub/static` folder then it should work 🤔

**Comment by DrewML** [comment]
@dweerd it's totally possible. However, you _really_ want to make sure that the bundles are built from the _exact_ same source. So you'd want to make sure that the output of static content deploy is identical, byte-for-byte, between the 2 machines.
