### ISSUE TITLE
MiniCart, Cart, Checkout Not Working

### ISSUE THREAD

**Issue by ramesh-durairajaram** [magento/baler#28]
After setting up baler. I am experiencing the following errors
- MiniCart not loading [After adding product]
![Home Page](https://user-images.githubusercontent.com/54365205/70629532-23b13980-1c50-11ea-83fe-4f7476d64c13.png)

- Order Summary not loading in CartPage
![Cart](https://user-images.githubusercontent.com/54365205/70629603-42173500-1c50-11ea-9f82-b4b0363f4a2e.png)

- Checkout page not loading
![Checkout](https://user-images.githubusercontent.com/54365205/70629549-290e8400-1c50-11ea-9add-018d8c8abeb8.png)

**Comment by wigman** [comment]
It would be helpful to have the errors that you get in your inspector -> console. Without it there's no way to tell what's happening.

**Comment by ramesh-durairajaram** [comment]
> It would be helpful to have the errors that you get in your inspector -> console. Without it there's no way to tell what's happening.

Hi Wigman, 
I apologise, please find the below errors log.
- [Checkout.log](https://github.com/magento/baler/files/3960511/Checkout.log)
- [Cart.log](https://github.com/magento/baler/files/3960512/Cart.log)
- [MiniCart.log](https://github.com/magento/baler/files/3960513/MiniCart.log)

Thanks in advance.

**Comment by wigman** [comment]
Okay. SetConf error means you’re missing a patch for the cookie dependency. Look for the other issue in this repo where the patches are linked. Otherwise wait for Monday, then I release a bundling guide including the patches. I will make sure to link it here.

**Comment by wigman** [comment]
@ramesh-durairajaram it's in this issue https://github.com/magento/baler/issues/6
Otherwise, I'll have all patches including documentation released on monday

**Comment by ramesh-durairajaram** [comment]
> @ramesh-durairajaram it's in this issue #6
> Otherwise, I'll have all patches including documentation released on monday

Thanks @wigman , I have applied the patch for now and It works. Thank you so much once again.
