### ISSUE TITLE
text! -prefix only works for HTML files

### ISSUE THREAD

**Issue by henkelund** [magento/baler#37]
Hi!

First of all, thank you working on Baler. I'm not using it in production yet but preliminary results are looking promising!

I've had it working with only minor hick-ups on 2.3.3 but this morning I tried to build 2.3.4 and got a crash in the frontend. It seems like Baler assumes that `text!`-dependencies are always HTML files and so things like `'text!js-translation.json'` ([introduced here](https://github.com/magento/magento2/commit/8e3f3ace6f9303f4b7a404ae7e08ac917934300b#diff-91596c50ea4783d8b5943deb1b03fa75R7)) doesn't work.

I did the simplest fix I could think of just to fix my crash:
```diff
diff --git a/src/createBundleFromDeps.ts b/src/createBundleFromDeps.ts
index 897a047..3fab6f4 100644
--- a/src/createBundleFromDeps.ts
+++ b/src/createBundleFromDeps.ts
@@ -58,12 +58,13 @@ async function getFinalModuleSource(
     const path = join(baseDir, resolver(dep).modulePath);
     const source = await readFile(path, 'utf8');
     const isHTML = extname(path) === '.html';
+    const isJSON = extname(path) === '.json';
     const shims = getShimsForModule(dep, requireConfig);
     const hasDefine = isAMDWithDefine(source);
     const isNamed = isNamedAMD(source);
     const hasInvalidShim = hasDefine && !!shims;
 
-    if (isHTML) {
+    if (isHTML || isJSON) {
         return { dep, file: wrapTextModule(dep, source), hasInvalidShim };
     }
```

But I suppose a better long-term fix would be to look at the `text!`-prefix instead of the file extension. What do you think?

Cheers!

**Comment by DrewML** [comment]
Hey @henkelund,

Thanks for the super well-written bug report! Would love to get this fixed, and your digging sure did save some time.

Was able to replicate this by adding the following unit test to [`createBundleFromDeps.unit.js`](https://github.com/magento/baler/blob/bdd0155c36f10788af8b3d7d89f811ffbd95d839/src/__tests__/createBundleFromDeps.unit.js) locally:

```js
test('non-html file loaded with text plugin gets wrapped as text module', async () => {
    stubFilePaths({
        'root/js-translation.json': '{"hello": "world" }',
    });
    stubDateISOString();
    const { createBundleFromDeps } = getModuleUnderTest();

    const results = await createBundleFromDeps(
        'core-bundle',
        ['text!js-translation.json'],
        'root',
        {},
        'Vendor/theme',
    );

    expect(results.bundle).toMatchSnapshot();
});
```

This generated the following output:

```js
define('text!js-translation.json', function() {
    // baler-injected stub for non-AMD module (no shim config was found for this module)
});
// Original code for non-AMD module text!js-translation.json
{\\"hello\\": \\"world\\" }"
`;
```

Clearly this isn't what we want 😂

I _think_ that I originally had the check for `.html` because the `dep` param passed to `getFinalModuleSource` did _not_ include the plugin string. Luckily, that was changed in b812523bd6 to fix some other `text!` bugs.

I opened up #38 to fix this. Can you pull it down and verify it resolves the problem you're having?

**Comment by henkelund** [comment]
I have tested your branch and this is the effect it has on the resulting `core-bundle.js`:

```diff
diff --git a/core-bundle.js b/core-bundle.js
index 6f4ab61..7595b62 100644
--- a/core-bundle.js
+++ b/core-bundle.js
@@ -6412,7 +6412,9 @@ define("Magento_Translation/js/mage-translation-dictionary", ["text!js-translati
     "use strict";
     return JSON.parse(e)
 }),
-define("text!js-translation.json", function() {}),
+define("text!js-translation.json", function() {
+    return "[]"
+}),
 define("text", ["module"], function(e) {
     "use strict";
     var t = /^\s*<\?xml(\s)+version=[\'\"](\d)*.(\d)*[\'\"](\s)*\?>/im
```

Instead of an empty function being generated, a JSON-encoded string is returned, as expected.

Thank you for your swift attention to this issue!
