### ISSUE TITLE
PHP requirement not documented

### ISSUE THREAD

**Issue by Parakoopa** [magento/baler#44]
It seems that baler needs a PHP executable. This is not documented. Of course if you work with Magento you usually also have PHP installed, but I was building a Docker image for baler and didn't realize that PHP was also directly required for executing baler.

It would be great, if the documentation included that information.

Also why does baler need a PHP executable...?

**Comment by DrewML** [comment]
Thanks for the report, @Parakoopa.

Happy to accept a PR for a docs update.

> Also why does baler need a PHP executable...?

https://github.com/magento/baler/blob/58759dd288e1ea50740346c0eb3a212296574071/src/magentoInterop.ts#L19-L22

**Comment by DrewML** [comment]
Looks like I used to have this documented and then lost it - whoops!

https://github.com/magento/baler/blob/c0c3bac9ff6801c984e41b3e4964255edc4107c4/README.md#L38
