### ISSUE TITLE
Stuck on creating core bundle file

### ISSUE THREAD

**Issue by omwro** [magento/baler#57]
I have been struggling with getting baler working in my magento 2 store where i did run de build command but stays stuck at creating core bundle file. It has been running for 24 hours now. I have also followed multiple tutorials on how to install it so im sure where it goes wrong.

Screenshot: https://prnt.sc/rzdeo8

**Comment by Quazz** [comment]
@omwro Try generating a trace file and put it here.

`baler build --trace`

**Comment by mdelandgraaf** [comment]
I have the same issue. Here is the last part of my trace file:

(1801.4147800207138): Resolving dependency "knockoutjs/knockout-repeat" from "unknown source"
(1801.4603910446167): Resolving dependency "knockoutjs/knockout-fast-foreach" from "unknown source"
(1801.503604054451): Resolving dependency "Magento_Ui/js/lib/knockout/bindings/color-picker" from "unknown source"
(1801.570688009262): Resolving dependency "spectrum" from "unknown source"
(1801.6110690832138): Resolving dependency "tinycolor" from "unknown source"
(1801.6504310369492): Resolving dependency "Magento_Ui/js/lib/knockout/extender/observable_array" from "unknown source"
(1801.716705083847): Resolving dependency "mage/translate-inline" from "unknown source"
(1801.7718710899353): Resolving dependency "jquery-ui-modules/dialog" from "unknown source"
(1801.819550037384): Resolving dependency "jquery-ui-modules/button" from "unknown source"
(1801.8651530742645): Resolving dependency "jquery-ui-modules/draggable" from "unknown source"
(1801.909686088562): Resolving dependency "jquery-ui-modules/position" from "unknown source"
(1801.9592870473862): Resolving dependency "Softwareimc_Videos/js/init" from "unknown source"
(1802.0111030340195): Resolving dependency "Softwareimc_Videos/js/video.min" from "unknown source"
(1802.0658520460129): Resolving dependency "Softwareimc_Videos/js/jquery.infinitescroll" from "unknown source"
(1802.1121660470963): Resolving dependency "Magento_Theme/js/responsive" from "unknown source"
(1802.1659010648727): Resolving dependency "matchMedia" from "unknown source"
(1802.2017951011658): Resolving dependency "mage/tabs" from "unknown source"
(1802.2421300411224): Resolving dependency "mage/collapsible" from "unknown source"
(1802.2822360992432): Resolving dependency "js/mage/collapsible-mixin" from "unknown source"
(1802.3348180055618): Resolving dependency "jquery/jquery-storageapi" from "unknown source"
(1802.3800240755081): Resolving dependency "jquery/jquery.cookie" from "unknown source"
(1802.4304810762405): Resolving dependency "jquery/jquery.storageapi.min" from "unknown source"
(1802.472846031189): Resolving dependency "Magento_Theme/js/theme" from "unknown source"
(1802.5244880914688): Resolving dependency "mage/smart-keyboard-handler" from "unknown source"
(1802.571513056755): Resolving dependency "mage/ie-class-fixer" from "unknown source"
(1802.6152200698853): Resolving dependency "Onestepcheckout_Iosc/js/postcode-shipping-field" from "unknown source"
(1802.6650130748749): Resolving dependency "js/functions" from "unknown source"
(1802.7280900478363): Resolving dependency "jquery.bootstrap" from "unknown source"


So i had this as last line before:
 (1802.7280900478363): Resolving dependency "owlcarousel" from "unknown source"
So i removed the owlcarousel from the site however now it is stuck on the line above it. It seems it only shows in the trace what dependency is resolved instead what is causing the problem?
